apiVersion: v1
kind: Service
metadata:
    name: "guofeitest-9803"
    labels:
        app: "guofeitest-9803"
spec:
    type: LoadBalancer
    ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
    selector:
        app: "guofeitest-9803"